### ISSUE TITLE
Migrating from Python to Swift results in already run scripts being ran again

### ISSUE THREAD

**Issue by WardsParadox** [macadmins/outset#1]
If a device has already had login scripts ran, migrating to this newer Swift version will run the same scripts again.

An error in the packaged version:
```
/usr/local/outset/outset --login
ERROR: plist import failed
INFO:
```
Looks also like it's also not writing to the same levels as the python preferences:

```
defaults read ~/Library/Preferences/com.github.outset.once
{
    "/usr/local/outset/login-once/first_time_setup.py" = "2023-01-12 12:58:59 +0000";
    "override_login_once" =     {
        "/usr/local/outset/login-once/first_time_setup.py" = "2023-01-12 20:55:48 +0000";
    };
}
```

This may already be fixed in newer versions, but logging as issue in case it's not

**Comment by WardsParadox** [comment]
Confirmed beta2 build still an issue. Taking a dive in to see if I can figure it out.

**Comment by bartreardon** [comment]
ah cool - yeah it will be looking in the wrong spot in the plist and of course doesn't recognise previous entries - should be easy to fix up

**Comment by bartreardon** [comment]
ok - should look look like this for the run_one plist?

```
% defaults read ~/Library/Preferences/com.github.outset.once.plist                  
{
    "/usr/local/outset/login-once/test.sh" = "2023-01-13 09:16:03 +0000";
    "/usr/local/outset/login-once/test2.sh" = "2023-01-13 09:18:36 +0000";
}

```

**Comment by bartreardon** [comment]
can you confirm this one looks fine compared to what you have?

```
% defaults read /usr/local/outset/share/com.chilcote.outset.plist       
{
    "ignored_users" =     (
        jack,
        jill,
        bob,
        bill
    );
    "network_timeout" = 280;
    "override_login_once" =     {
        "someothershell.sh" = "2022-12-01 21:09:17 +0000";
        "someshell.sh" = "2022-12-01 21:09:02 +0000";
    };
    "wait_for_network" = 0;
}
```

**Comment by bartreardon** [comment]
updated build
[Outset.pkg.zip](https://github.com/bartreardon/outset/files/10410153/Outset.pkg.zip)

**Comment by bartreardon** [comment]
try this build 
[Outset.pkg.zip](https://github.com/bartreardon/outset/files/10410496/Outset.pkg.zip)

**Comment by WardsParadox** [comment]
Trying today. Sorry was under the weather this weekend.

**Comment by WardsParadox** [comment]
```
Timestamp                       Thread     Type        Activity             PID    TTL
2023-01-19 09:49:35.571613-0800 0x436c52   Error       0x0                  55146  0    outset: [com.github.outset:main] runonce plist import failed
2023-01-19 09:49:36.339135-0800 0x436c52   Info        0x0                  55146  0    outset: [com.github.outset:main]
```

**Comment by WardsParadox** [comment]
Have you tried using CFpreferences to read in the plist data instead of raw importing?

**Comment by bartreardon** [comment]
I'm not against CFpreferences. - the nice thing about PropertyListDecoder() is reading and writing a data structure to wherever without worring about preference domains (e.g. writing to user pres as root or reading from the non usual locations.



> Timestamp                       Thread     Type        Activity             PID    TTL
> 2023-01-19 09:49:35.571613-0800 0x436c52   Error       0x0                  55146  0    outset: [com.github.outset:main] runonce plist import failed
> 2023-01-19 09:49:36.339135-0800 0x436c52   Info        0x0                  55146  0    outset: [com.github.outset:main]

Was this a result of running as root or as user (I'll need to add more details to the log as the runonce plist location will be different depending on who runs it)

If run as root, the runonce plist will be  `/usr/local/outset/share/com.github.outset.once.<uid of the user>.plist`. `/usr/local/outset/share` should have perms `755` and the contents should all be `644` with owner being root

If run as the user the plist is in `/Users/<username>/Library/Preferences/com.github.outset.once.plist` and should be owned by the user with perms 600.

**Comment by WardsParadox** [comment]
I ran `/usr/local/outset/outset --login` as the user. we only have one script that runs as privileged. It's the user level plist that fails to import and acknowledge that it's already ran.

**Comment by bartreardon** [comment]
hmm - ok - I'll take a look and troubleshoot - thanks for getting back (and for the testing 🙂  - much appreciated)

**Comment by bartreardon** [comment]
@WardsParadox you able to verify the behaviour using beta 1? https://github.com/macadmins/outset/releases/tag/v4.0-Beta-1 

You will likely see tasks run again as a result of the install (re-loading the launchd items will trigger any scripts present in any of the boot/login directories to run) but it should respect boot/login once items.

**Comment by WardsParadox** [comment]
```sh
/usr/local/outset/outset --login-once
ERROR: legacy Preferences migration failed
```

still failing to migrate.

**Comment by bartreardon** [comment]
you able to shoot me a copy of the existing preferences file?

**Comment by WardsParadox** [comment]
I would but it seems the migration deleted my old preferences :/

**Comment by bartreardon** [comment]
hmm - if you `defaults read io.macadmins.Outset` and `sudo defaults read io.macadmins.Outset` does it show all your stuff? (you might need to reference `/var/root/Library/Preferences/io.macadmins.Outset.plist` directly but see how you go)

keeping a backup of the old settings though is probably a good idea before I do the migrating 🤔

**Comment by WardsParadox** [comment]
Oh...the new preferences. 🤦🏻 
Login-once:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>run_once</key>
	<dict>
		<key>/usr/local/outset/login-once/first_time_setup.py</key>
		<date>2023-01-19T17:49:36Z</date>
	</dict>
</dict>
</plist>

```


sudo defaults
```
{
    ignoredUsers =     (
    );
    networkTimeout = 0;
    overrideLoginOnce =     {
    };
    waitForNetwork = 0;
}
```

**Comment by bartreardon** [comment]
This should be ok in the [4.0 release](https://github.com/macadmins/outset/releases/tag/v4.0.21874) - LMK if it's not doing what you think it should.

**Comment by WardsParadox** [comment]
Checking now

**Comment by WardsParadox** [comment]
Migration looks great. Found a new error, but will log as separate issue.

**Comment by bartreardon** [comment]
Cool - Closing this as done then
