### ISSUE TITLE
Outset passing arguments to scripts resulting in unexpected script argument errors

### ISSUE THREAD

**Issue by WardsParadox** [macadmins/outset#22]
**Describe the bug**
Installed the new version of outset. Ran `outset --login` to test our login scripts.

Most scripts ran fine, but we have a script that has a specific set of optional arguments that is now failing due to being passed what looks like additional arguments.

**To Reproduce**
Deploy script to login-privilaged* directories (either works).

**Expected behavior**
Script runs as expected.

**Screenshots**
```log
2023-05-10 14:07:34.638000-0700 0xca1f40   Debug       0x0                  97660  0    Outset: [io.macadmins.Outset:main] Completed task /usr/local/outset/login-privileged-every/upgradeWatcher.py with status 2
2023-05-10 14:07:34.638075-0700 0xca1f40   Debug       0x0                  97660  0    Outset: [io.macadmins.Outset:main] Task output:
2023-05-10 14:07:34.638103-0700 0xca1f40   Error       0x0                  97660  0    Outset: [io.macadmins.Outset:main] usage: upgradeWatcher.py [-h] [--testfile TESTFILE]
                         [--testosversion TESTOSVERSION]
upgradeWatcher.py: error: unrecognized arguments: mczack
```

**System Details:**
 - OS: macOS 12.6.5 and macOS 13.4 RC
 - arm64
 - Version 4.0.0-b2 (this looks to not have gotten updated with latest package release)

**Additional context**
N/A

**Comment by bartreardon** [comment]
ok - could be because all scripts get passed the current logged in user as argument 1.

Will need to think about how to manage that behaviour. is `upgradeWatcher.py` something that is public or can be shared?

**Comment by WardsParadox** [comment]
Unfortunately, not at this point in time.

**Comment by bartreardon** [comment]
You happy to work around with the knowledge that all scripts in v4 have the console user passed in as the first script argument?

I've documented that behaviour here https://github.com/macadmins/outset/wiki/FAQ#script-processing

**Comment by WardsParadox** [comment]
I think so. I think we should document and maintain a method that works in case additional variables are added :) 
Shell scripts don't really care, but python and argparse can get thrown from it. Example code

```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("user", metavar="user", nargs=1, help="User to run against, used by outset", default=None)
args = parser.parse_args()
print(args)

> Namespace(user=['mczack'])
```

**Comment by WardsParadox** [comment]
Updated the wiki to cover this. Resolving.
