### ISSUE TITLE
Running on-demand script after first login fails

### ISSUE THREAD

**Issue by fponcelin** [macadmins/outset#27]
Running an on-demand script with Outset 4.0.21874 after the first login (right after completing Setup Assistant) with the command `/usr/local/outset/outset --on-demand` results in the following output: `INFO: User [currentUser] is not the current console user. Skipping on-demand run.` (replace [currentUser] with the actual logged in local username).

Attempting to run the on-demand script by doing `/usr/bin/touch /private/tmp/.io.macadmins.outset.ondemand.launchd` has no visible effect.

To troubleshoot, I ran `who | grep 'console' | awk '{print $1}'` and got the following output:
```
_mbsetupuser
[currentUser]
```

I suspect the _mbsetupuser account still being active at this point in time is causing confusion.

**Comment by bartreardon** [comment]
Correct. This is a protection so that on demand scripts can't be run by a user that is not the current console user. More details on how on demand processing works [in the wiki](https://github.com/macadmins/outset/wiki/OnDemand)

At what point is your on demand script being initiated?

**Comment by bartreardon** [comment]
Right. So what's happening (I think) is your deployment script is still the parent process that kicks off the on-demand. That will result in the mismatch between who the console user is and who the _current_ user (i.e. the account running the script) is. 

For user level scripts, `$1` will be the current user account running the script. If that value matches what you expect it should be ok.

Are you able to post an example that replicates the issue you are seeing along with the workflow up to to the point the script runs?

**Comment by fponcelin** [comment]
Actually I also tried to manually trigger outset from Terminal as the current user, and got the same output (`INFO: User [currentUser] is not the current console user. Skipping on-demand run.`).

So I think the crux of the issue is twofold:
- It's only happening after the first login following Setup Assistant. After rebooting the issue resolves itself and cannot be reproduced.
- The `who` command used by Outset to get the console user (`let consoleUserName = runShellCommand("who | grep 'console' | awk '{print $1}'").output` line 112 of `SystemUtils.swift`) outputs two lines, with `_mbsetupuser` as the first line (I don't know how Swift handles that output in the code - not familiar enough with the language).

So my suggestion would be to try replacing that command with `echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }'` (I did not come up with that line, that credit goes to the the wonderful Armin: https://scriptingosx.com/2019/09/get-current-user-in-shell-scripts-on-macos/ 😉).

**Comment by dhmoore** [comment]
I'd suggest this for getting the current console user:
`import SystemConfiguration

var uid: uid_t = 0
var gid: gid_t = 0
let consoleUserInfo = SCDynamicStoreCopyConsoleUser(nil, &uid, &gid)`

**Comment by bartreardon** [comment]
lol - I use `SCDynamicStoreCopyConsoleUser` in another project and didn't think to use it here :/

**Comment by bartreardon** [comment]
Can you check [this build](https://github.com/macadmins/outset/releases/tag/v4.0.21885) and let me know if it resolves your issue.

**Comment by fponcelin** [comment]
Yes! It's working perfectly now 😃

**Comment by bartreardon** [comment]
awesome, cheers 🙂

**Comment by fponcelin** [comment]
I assume I can close the issue now! Thanks for the quick and elegant resolution 😊
