### ISSUE TITLE
Login Items Show 2 different entries for Outset

### ISSUE THREAD

**Issue by lincolnep** [macadmins/outset#28]
**Describe the bug**
Login Items Show 2 different entries for outset but I think there should only be one.

**To Reproduce**
Install Outset and check Login Items

**Expected behavior**
From the Wiki I was only expecting 1 Login Item entry for Outset

**Screenshots**
<img width="329" alt="image" src="https://github.com/macadmins/outset/assets/3850303/de3bc383-24c3-4320-af10-4215161dd0bf">
<img width="328" alt="image" src="https://github.com/macadmins/outset/assets/3850303/7a77941e-adcf-414f-b999-bcffaaf41c5f">

**System Details:**
 - OS: 13.3.1
 - Architecture: Intel
 - Version: 4.0.21874

**Additional context**
Not sure if this is an issue but I thought I would ask.

**Comment by lincolnep** [comment]
After installing Outset version 4.0.21885 it update the icon in login items
<img width="327" alt="image" src="https://github.com/macadmins/outset/assets/3850303/512b3360-e86c-491a-9d89-87b2fb7b7723">

**Comment by lincolnep** [comment]
This is my current Login Items MDM setup
<img width="689" alt="image" src="https://github.com/macadmins/outset/assets/3850303/3c8e339b-8371-499b-8f4d-d03c02d6ebb8">

**Comment by bartreardon** [comment]
This is a known issue as per the wiki https://github.com/macadmins/outset/wiki/Deployment#known-issues-and-behaviour

**Comment by lincolnep** [comment]
Thank you, bartreardon, for pointing out that part of the wiki that I missed.

I have followed the instructions mentioned in the wiki to address the issue, but unfortunately, it did not resolve it.

Furthermore, I am facing difficulty in preventing users from disabling Outset in login items, especially when those items are not listed under Outset. Do you have any suggestions or ideas on how to prevent users from disabling Outset in such cases?

**Comment by bartreardon** [comment]
instead of using bundle id to control the login items you could use label prefix `io.macadmins.Outset` or teamID `T4SK8ZXCXG`

**Comment by lincolnep** [comment]
Thanks bartreardon that did the trick!

Both ways work well as an added caution I used both like this.
<img width="600" alt="image" src="https://github.com/macadmins/outset/assets/3850303/63e49209-a3dd-498c-a2fe-4888da61f871">

**Comment by bartreardon** [comment]
Good to know 🙂 I might add that to the wiki
