### ISSUE TITLE
'overide' OPTIONS should be 'override' to maintain compatibility with earlier versions

### ISSUE THREAD

**Issue by mrowell** [macadmins/outset#31]
In versions less than 4 the override options were:
--add-override and --remove-override
See [outset.py](https://github.com/macadmins/outset/blob/0e5167db8dff43eb1b18db0931a34d4723bf56f7/legacy/pkgroot/usr/local/outset/outset.py#L421)

In version 4 they are missing an 'r' 
--add-overide and --remove-overide

The [wiki](https://github.com/macadmins/outset/wiki/ScriptOverrides ) also documents them as --add-override and --remove-override  

To maintain compatibility with earlier versions the options should be changed

**Comment by bartreardon** [comment]
I blame my proof reader....who also happens to be my developer.
