### ISSUE TITLE
--add-override no longer works

### ISSUE THREAD

**Issue by miawri** [macadmins/outset#38]
**Describe the bug**
running /usr/local/outset/outset --add-override <scriptname> doesn't add the override as expected

however

running /usr/local/outset/outset --add-overide <scriptname> returns
DEBUG: Adding <scriptpath>/<scriptname> to overide list

**To Reproduce**
/usr/local/outset/outset --add-override <scriptname> returns nothing

**Expected behavior**
/usr/local/outset/outset --add-override <scriptname> should return
DEBUG: Adding <scriptpath>/<scriptname> to ove(r?)ride list

**Comment by bartreardon** [comment]
can you check out this release and let me know if there's any issues.

https://github.com/macadmins/outset/releases/tag/v4.1.1.21915

**Comment by miawri** [comment]
Yes, that has fixed it.

Thanks!

**Comment by bartreardon** [comment]
cool - I'll see if there are any other minor bugs and then do a release after the weekend.
