### ISSUE TITLE
Delete Local Profile install functionality as it is no longer supported

### ISSUE THREAD

**Issue by natewalck** [macadmins/outset#4]
Delete all the local profile install related code as local installs of profiles are not supported on macOS anymore.

**Comment by bartreardon** [comment]
https://github.com/macadmins/outset/blob/main/outset/Functions/Processing.swift#L22
https://github.com/macadmins/outset/blob/main/outset/Functions/Processing.swift#L40
https://github.com/macadmins/outset/blob/main/outset/Functions/Processing.swift#L84
https://github.com/macadmins/outset/blob/main/outset/Functions/Processing.swift#L181

+ any mentions of "profile" or "mobileconfig" in help or documentation

**Comment by BigMacAdmin** [comment]
According to Nate even someone swift illiterate such as myself can help with this, I'm willing to give it a shot.

**Comment by natewalck** [comment]
This is completed by #8

**Comment by kevinmcox** [comment]
I removed all references to configuration profile support from the Wiki.
