### ISSUE TITLE
Overrides not being added correctly

### ISSUE THREAD

**Issue by RedClawx** [macadmins/outset#41]
When adding an override the path is not getting recorded correctly into the preference file. I am following the instruction from https://github.com/macadmins/outset/wiki/ScriptOverrides. I am attempting to add two overrides. If the script is located in the "login-once" folder it gets added correctly. If the script is located in the "login-privileged-once" it does not get added correctly. The commands used are as follows:

```
sudo /usr/local/outset/outset --add-override /usr/local/outset/login-once/Remove_MS_Office_VL_User.sh
sudo /usr/local/outset/outset --add-override /usr/local/outset/login-privileged-once/Remove_MS_Office_VL_System.sh
```

When I look at the /Library/Preferences/io.macadmins.Outset.plist file the results are as follows:

	<key>override_login_once</key>
	<dict>
		<key>/usr/local/outset/login-once//usr/local/outset/login-privileged-once/Remove_MS_Office_VL_System.sh</key>
		<date>2023-11-16T19:25:46Z</date>
		<key>/usr/local/outset/login-once/Remove_MS_Office_VL_User.sh</key>
		<date>2023-11-16T19:26:01Z</date>
	</dict>

**Comment by bartreardon** [comment]
This was merged back in April but the issue was never closed. Will close now but if it's still an issue, please re-open.
