### ISSUE TITLE
No instructions/information about what to do with systems already running legacy outset

### ISSUE THREAD

**Issue by naneko** [macadmins/outset#43]
I have many systems running legacy outset. There's no documentation indicating if I need to do anything (uninstall, disable, etc...) before installing Outset 4.0. It would be nice to have this in the FAQ or something.

**Comment by naneko** [comment]
It seems this is just seamlessly taken care of either by the installer or the new version of Outset. Still might be worth a mention on the wiki but I'm going to close this issue.

**Comment by bartreardon** [comment]
correct on both counts - the installer and outset binary try to move everything over for you. 

if you do that and something doesn't move as you'd expect then please raise that as an issue
