### ISSUE TITLE
Log script errors and failures to log file

### ISSUE THREAD

**Issue by naneko** [macadmins/outset#44]
Right now script outputs and status is only logged with verbose mode on. I think this makes sense when scripts run without issue. However I think if a script writes to stderr or ends with a non-zero exit code it should be logged.

I'm not super well versed in Swift but if I have a moment I'll create a pull request to add this.

**Comment by bartreardon** [comment]
it is. everything gets sent to `/usr/local/outset/logs`

I could expand the log file system so seperat event types get their own log file but for now it all dumped to `outset.log` in that directory
