### ISSUE TITLE
Outset should ignore .DS_Store files

### ISSUE THREAD

**Issue by seanchristians-vention** [macadmins/outset#46]
If Outset is configured to verify checksums and a .DS_Store file happens to exist in out of the Outset directories, an error is printed to the log.

This doesn't seem to cause any problems with processing other scripts, but it would be nice if Outset would simply ignore that file.

For my build process, I wrote a script to copy all of my scripts from a local repo into the Outset folder and then use outset-pkg to make the installer. When I copy those files, sometimes a .DS_Store can be included. Obviously I've improved my own build script to exclude .DS_Store files, but I think it would be nice if Outset ignored them by default.

Thanks for reading!

**Comment by bartreardon** [comment]
I've thought about this for a bit and I've decided to close this as wontfix.

The reason being that outset is not impacted by the presence of `.DS_Store` files but will result in an error to the log. This behaviour is preferred to ensure your deployments are clean. As you have indicated, the presence of the error message forced you to improve your process. If no error were thrown in the presence of files that were not supposed to be there then you would not have noticed.

That is to say, we want outset to notify us when our file structure is not how it should be, but also errant files should not impact regular operation.
